### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/dna-monitor#19]

**Comment by mr-illu** [comment]
the guys from dolce fumo in kirchheim teck asked for a linux version too...

**Comment by hobbyquaker** [comment]
will come soon, is only a little change in finding the right serial port.

**Comment by shagu** [comment]
On Archlinux:
```
# pacman -Sy nodejs npm
# chmod 777 /dev/ttyACM0
```

```
$ npm install
$ ./node_modules/.bin/electron .
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x2addda25f7a0)" of type `gboolean'
App threw an error during load
Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/eric/dna-monitor/node_modules/bindings/bindings.js:76:44)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/eric/dna-monitor/node_modules/bindings/bindings.js:76:44)
```

The console is called: `/dev/ttyACM0`

**Comment by hobbyquaker** [comment]
ah, annoying issue with node-serialport and electron. should work if you rebuild it like that:
```
npm install electron-rebuild
./node-modules/.bin/electron-rebuild serialport
```

**Comment by hobbyquaker** [comment]
d549e113d79ea552e391275151014b7487ddc6f7 serialport should be found now

**Comment by shagu** [comment]
Works like a charm

**Comment by hobbyquaker** [comment]
First linux builds for testing are available here:
https://github.com/hobbyquaker/dna-monitor/releases/tag/v1.1.0-beta2
